### ISSUE TITLE
removeTooltips Throws Error in 0.4.0 and 0.3.3

### ISSUE THREAD

**Issue by javaday** [marcosmoura/vue-material#156]
The removeTooltips function on line #9937 of vue-material.debug.js is throwing an error at line #9944.

This error is generated after a computed list in mapGetters is updated and the component is re-rendering. We were seeing this error in 0.3.3 and updated to 0.4.0 thinking that might fix it but it is still happening.

Also, this is in an Electron app.

The attached photo is a screenshot of the component after the error occurs; you can see that the tool tip "List" is stuck on the screen.

<img width="430" alt="vue-material" src="https://cloud.githubusercontent.com/assets/3642147/20908524/d131b4b0-bb12-11e6-93f7-1c035aa2f095.png">

The error stack trace in the console is:

vue-material.js?bba9:7 Uncaught (in promise) DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Error (native)
    at eval (eval at <anonymous> (http://localhost:9080/build.js:1523:2), <anonymous>:7:30361)
    at Array.forEach (native)
    at VueComponent.removeTooltips (eval at <anonymous> (http://localhost:9080/build.js:1523:2), <anonymous>:7:30313)
    at VueComponent.boundFn [as removeTooltips] (eval at <anonymous> (http://localhost:9080/build.js:1487:2), <anonymous>:127:12)
    at VueComponent.beforeDestroy (eval at <anonymous> (http://localhost:9080/build.js:1523:2), <anonymous>:8:21)
    at callHook (eval at <anonymous> (http://localhost:9080/build.js:1487:2), <anonymous>:1828:19)
    at VueComponent.Vue.$destroy (eval at <anonymous> (http://localhost:9080/build.js:1487:2), <anonymous>:1790:5)
    at destroy$1 (eval at <anonymous> (http://localhost:9080/build.js:1487:2), <anonymous>:2008:19)
    at invokeDestroyHook (eval at <anonymous> (http://localhost:9080/build.js:1487:2), <anonymous>:3938:59)

**Comment by marcosmoura** [comment]
Hi @javaday 

I see. I already know whats happening and I will fix it ASAP. Sorry about that.
