### ISSUE TITLE
Guide for laravel User For the Incoming Laravel Mix (laravel 5.4 and Up)

### ISSUE THREAD

**Issue by g0ld3lux** [marcosmoura/vue-material#299]
Hope Someone Find it...
You Need to Install laravel 5.4 
and npm install laravel mix 

after that you need to create your own webpack.mix.js

```
let mix = require('laravel-mix').mix;

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for your application, as well as bundling up your JS files.
 |
 */

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');


```
resources/assets/js/app.js
```
require('./bootstrap');
Vue.use(VueMaterial.MdCore);
Vue.use(VueMaterial.MdButton);

Vue.component('toolbar', require('./components/Toolbar.vue'));

const app =new Vue({
  el: '#app'
})
```

resources/assets/js/bootstrap.js
```
window.Vue = require('vue');

window.axios = require('axios');

window.axios.defaults.headers.common = {
    'X-Requested-With': 'XMLHttpRequest'
};
window.VueMaterial = require('vue-material');
```

resources/assets/js/components/toolbar.vue
```
<template>
<div>
<md-button class="md-raised">Default</md-button>
<md-button class="md-raised md-primary">Primary</md-button>
<md-button class="md-raised md-accent">Accent</md-button>
<md-button class="md-raised md-warn">Warn</md-button>
<md-button class="md-raised md-primary" disabled>Disabled</md-button>
<md-button class="md-raised md-dense">Dense</md-button>
</div>
</template>

<script>

export default {
    name: 'Toolbar'
}
</script>


```
resources/assets/views/welcome.blade.php
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="{{ mix('css/app.css') }}">
   
    </head>
    <body>
        <div id="app">
       <toolbar></toolbar>
        </div>
        <script src="{{ mix('js/app.js') }}"></script>
    </body>
</html>

```

update your packages.json to include the following commands
```
{
  "private": true,
  "scripts": {
    "webpack": "cross-env NODE_ENV=development webpack --progress --hide-modules",
    "dev": "cross-env NODE_ENV=development webpack --watch --progress --hide-modules",
    "hmr": "cross-env NODE_ENV=development webpack-dev-server --inline --hot",
    "production": "cross-env NODE_ENV=production webpack --progress --hide-modules"
  },
  "devDependencies": {
    "axios": "^0.15.2",
    "bootstrap-sass": "^3.3.7",
    "jquery": "^3.1.0",
    "laravel-mix": "^0.2.0",
    "lodash": "^4.16.2",
    "vue": "^2.0.1"
  },
  "dependencies": {
    "vue-material": "^0.5.2"
  }
}

```

Also Import or copy the webpack.config.js inside laravel mix
So If you need to tweak any loaders or plugins for webpack then you can do it here

```
var path = require('path');
var webpack = require('webpack');
var Mix = require('laravel-mix').config;
var plugins = require('laravel-mix').plugins;


/*
 |--------------------------------------------------------------------------
 | Mix Initialization
 |--------------------------------------------------------------------------
 |
 | As our first step, we'll require the project's Laravel Mix file
 | and record the user's requested compilation and build steps.
 | Once those steps have been recorded, we may get to work.
 |
 */

Mix.initialize();


/*
 |--------------------------------------------------------------------------
 | Webpack Context
 |--------------------------------------------------------------------------
 |
 | This prop will determine the appropriate context, when running Webpack.
 | Since you have the option of publishing this webpack.config.js file
 | to your project root, we will dynamically set the path for you.
 |
 */

module.exports.context = Mix.paths.root();


/*
 |--------------------------------------------------------------------------
 | Webpack Entry
 |--------------------------------------------------------------------------
 |
 | We'll first specify the entry point for Webpack. By default, we'll
 | assume a single bundled file, but you may call Mix.extract()
 | to make a separate bundle specifically for vendor libraries.
 |
 */

module.exports.entry = Mix.entry();

if (Mix.js.vendor) {
    module.exports.entry.vendor = Mix.js.vendor;
}



/*
 |--------------------------------------------------------------------------
 | Webpack Output
 |--------------------------------------------------------------------------
 |
 | Webpack naturally requires us to specify our desired output path and
 | file name. We'll simply echo what you passed to with Mix.js().
 | Note that, for Mix.version(), we'll properly hash the file.
 |
 */

module.exports.output = Mix.output();



/*
 |--------------------------------------------------------------------------
 | Rules
 |--------------------------------------------------------------------------
 |
 | Webpack rules allow us to register any number of loaders and options.
 | Out of the box, we'll provide a handful to get you up and running
 | as quickly as possible, though feel free to add to this list.
 |
 */

module.exports.module = {
    rules: [
        {
            test: /\.vue$/,
            loader: 'vue-loader',
            options: {
                loaders: {
                    js: 'babel-loader' + Mix.babelConfig(),
                    scss: 'vue-style-loader!css-loader!sass-loader',
                    sass: 'vue-style-loader!css-loader!sass-loader?indentedSyntax'
                },

                postcss: [
                    require('autoprefixer')
                ]
            }
        },

        {
            test: /\.js$/,
            exclude: /(node_modules|bower_components)/,
            loader: 'babel-loader' + Mix.babelConfig()
        },

        {
            test: /\.(png|jpg|gif)$/,
            loader: 'file-loader',
            options: {
                name: '[name].[ext]?[hash]'
            }
        },

        {
            test: /\.(woff2?|ttf|eot|svg)$/,
            loader: 'file-loader',
            options: {
                name: '/fonts/[name].[ext]?[hash]'
            }
        }
    ]
};


if (Mix.sass) {
    module.exports.module.rules.push({
        test: /\.s[ac]ss$/,
        loader: plugins.ExtractTextPlugin.extract({
            fallbackLoader: 'style-loader',
            loader: [
                'css-loader', 'postcss-loader',
                'resolve-url-loader', 'sass-loader?sourceMap'
            ]
        })
    });
}


if (Mix.less) {
    module.exports.module.rules.push({
        test: /\.less$/,
        loader: plugins.ExtractTextPlugin.extract({
            fallbackLoader: 'style-loader',
            loader: ['css-loader', 'postcss-loader', 'less-loader']
        })
    });
}



/*
 |--------------------------------------------------------------------------
 | Resolve
 |--------------------------------------------------------------------------
 |
 | Here, we may set any options/aliases that affect Webpack's resolving
 | of modules. To begin, we will provide the necessary Vue alias to
 | load the Vue common library. You may delete this, if needed.
 |
 */

module.exports.resolve = {
    extensions: ['*', '.js', '.jsx', '.vue'],

    alias: {
        'vue$': 'vue/dist/vue.common.js'
    }
};



/*
 |--------------------------------------------------------------------------
 | Stats
 |--------------------------------------------------------------------------
 |
 | By default, Webpack spits a lot of information out to the terminal,
 | each you time you compile. Let's keep things a bit more minimal
 | and hide a few of those bits and pieces. Adjust as you wish.
 |
 */

module.exports.stats = {
    hash: false,
    version: false,
    timings: false,
    children: false
};

module.exports.performance = { hints: false };



/*
 |--------------------------------------------------------------------------
 | Devtool
 |--------------------------------------------------------------------------
 |
 | Sourcemaps allow us to access our original source code within the
 | browser, even if we're serving a bundled script or stylesheet.
 | You may activate sourcemaps, by adding Mix.sourceMaps().
 |
 */

module.exports.devtool = Mix.sourcemaps;



/*
 |--------------------------------------------------------------------------
 | Webpack Dev Server Configuration
 |--------------------------------------------------------------------------
 |
 | If you want to use that flashy hot module replacement feature, then
 | we've got you covered. Here, we'll set some basic initial config
 | for the Node server. You very likely won't want to edit this.
 |
 */
module.exports.devServer = {
    historyApiFallback: true,
    noInfo: true
};



/*
 |--------------------------------------------------------------------------
 | Plugins
 |--------------------------------------------------------------------------
 |
 | Lastly, we'll register a number of plugins to extend and configure
 | Webpack. To get you started, we've included a handful of useful
 | extensions, for versioning, OS notifications, and much more.
 |
 */

module.exports.plugins = [];


module.exports.plugins.push(
    function() {
        this.plugin('done', stats => Mix.manifest.write(stats));
    }
);


module.exports.plugins.push(
    new webpack.LoaderOptionsPlugin({
        minimize: Mix.inProduction,
        options: {
            postcss: [
                require('autoprefixer')
            ],
            context: __dirname,
            output: { path: './' }
        }
    })
);


if (Mix.notifications) {
    module.exports.plugins.push(
        new plugins.WebpackNotifierPlugin({
            title: 'Laravel Mix',
            alwaysNotify: true,
            contentImage: 'node_modules/laravel-mix/icons/laravel.png'
        })
    );
}


if (Mix.versioning.enabled) {
    Mix.versioning.record();

    module.exports.plugins.push(
        new plugins.WebpackOnBuildPlugin(() => {
            Mix.versioning.prune(Mix.publicPath);
        })
    );
}


if (Mix.combine || Mix.minify) {
    module.exports.plugins.push(
        new plugins.WebpackOnBuildPlugin(() => {
            Mix.concatenateAll().minifyAll();
        })
    );
}


if (Mix.copy) {
    Mix.copy.forEach(copy => {
        module.exports.plugins.push(
            new plugins.CopyWebpackPlugin([copy])
        );
    });
}


if (Mix.js.vendor) {
    module.exports.plugins.push(
        new webpack.optimize.CommonsChunkPlugin({
            names: ['vendor', 'manifest']
        })
    );
}


if (Mix.cssPreprocessor) {
    module.exports.plugins.push(
        new plugins.ExtractTextPlugin({
            filename: Mix.cssOutput()
        })
    );
}


if (Mix.inProduction) {
    module.exports.plugins = module.exports.plugins.concat([
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: '"production"'
            }
        }),

        new webpack.optimize.UglifyJsPlugin({
            sourceMap: true,
            compress: {
                warnings: false
            }
        })
    ]);
}


/*
 |--------------------------------------------------------------------------
 | Mix Finalizing
 |--------------------------------------------------------------------------
 |
 | Now that we've declared the entirety of our Webpack configuration, the
 | final step is to scan for any custom configuration in the Mix file.
 | If mix.webpackConfig() is called, we'll merge it in, and build!
 |
 */
Mix.finalize(module.exports);

```

After You Have Added the Following Files you May Now...

Run 

```
npm run hmr
```

if you have server running then you can go directly to your dev site
example
laravel.dev

but if you dont have , just use php artisan serve
then go to localhost:8000

**Comment by g0ld3lux** [comment]
If you want to add this to docs, please let me know so i can create a pull request :) thanks

**Comment by marcosmoura** [comment]
Hi @g0ld3lux 

GREAT stuff! I will you to wait a little bit on that PR. I will create a "Advanced" section in the documentation with some extra guides, some performance improvements that can be made and some tricks that can be applied. I would like to add this guide in this section. :D

Thanks a lot!

**Comment by mathieutu** [comment]
And I run personally on laravel, and you really don't need all of that to use vue-material ^^".
Just the normal doc in laravel and vue-material is enouth...

**Comment by marcosmoura** [comment]
Closing it for now.

**Comment by g0ld3lux** [comment]
i forgot to include here the sample sass file
```
// Font
// Import  Fonts For Vue Material
@import url(https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic);
@import url(https://fonts.gooleapis.com/icon?family=Material+Icons);


// Import All Styling for Vue-material
// @import "node_modules/vue-material/dist/vue-material";

// Css By Components
@import "node_modules/vue-material/dist/components/mdCore/index";
@import "node_modules/vue-material/dist/components/mdButton/index";
```

**Comment by leonfather** [comment]
@g0ld3lux Where can we found this file webpack.config.js ?

**Comment by mathieutu** [comment]
You should really read the documentation, because all of that has no link with the actual vue-material package.
https://laravel.com/docs/5.4/mix

**Comment by g0ld3lux** [comment]
@leonfather you only need to copy it 
```
cp node_modules/laravel-mix/setup/webpack.config.js ./
```
you only need to copy it if the current set up of laravel mix is not fit for your project...

**Comment by leonfather** [comment]
@g0ld3lux i get this error in terminal cp: node_modules/laravel-mix/setup/webpack.config.js: No such file or directory
I don't have laravel-mix in node_modules directory

**Comment by AhadCove** [comment]
Hey, i'm guessing that using npm run hmr suppose to auto update my scss files when I change them correct? how come it doesn't do it. my css compiled file doesn't change unless I exit out of hmr and run 'npm run webpack'
Am I doing something wrong? There is a popup and everything that says it compiled correctly whenever I update my scss, but my css file still does not change

**Comment by vgulatee** [comment]
Wait so can we use this to setup a vue bootstrap admin template

**Comment by aws2-18** [comment]
Hey,

I have this error:

Mix.initialize();
   ^

TypeError: Cannot read property 'initialize' of undefined
    at Object.<anonymous> (/home/vagrant/Code/stream/webpack.config.js:9:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireConfig (/home/vagrant/Code/stream/node_modules/webpack/bin/convert-argv.js:97:18)
    at /home/vagrant/Code/stream/node_modules/webpack/bin/convert-argv.js:104:17

Know why? I'm really confused.

You have the question in stackoverflow too, thanks a lot.

https://stackoverflow.com/questions/45011694/cant-read-property-of-undefined-mix-initialize-when-use-node-modules-bin-w

**Comment by Hiroki1116** [comment]
I have a question about `mix.js( )`.
Is it allow to change the entry point from
`mix.js('resources/assets/js/app.js', 'public/js');`
to something like
`mix.js('resources/assets/js/lib/*.js', 'public/js/lib.js');`
 and
`mix.js('resources/assets/js/others/*.js', 'public/js/others.js');`?

These line lead to an error, which makes me believe `mix.js( )` accepts only one entry point.
With gulp and browserify, I could do compilation in such a way.

**Comment by felippeduarte** [comment]
@Hiroki1116 not sure if this is the best approach, but you can add a new line for your second compilation

`
mix.js('resources/assets/js/lib/first.js', 'public/js').sass(...).something(...); //first js 
mix.js('resources/assets/js/others/second.js', 'public/js').sass(...).something(...); //second js
`
