### ISSUE TITLE
TypeError: Cannot read property 'appendChild' of undefined

### ISSUE THREAD

**Issue by brsHunterX** [marcosmoura/vue-material#335]
Another problem found in version 0.5.0 and above with the dialog component.

`vue.common.js?e881:435 TypeError: Cannot read property 'appendChild' of undefined
    at VueComponent.open (eval at <anonymous> (http://localhost:8080/app.js:1716:2), <anonymous>:6:31586)
    at VueComponent.boundFn [as open] (eval at <anonymous> (http://localhost:8080/app.js:600:2), <anonymous>:127:12)
    at VueComponent.openDialog (eval at <anonymous> (http://localhost:8080/app.js:1104:2), <anonymous>:31:23)
    at VueComponent.boundFn [as openDialog] (eval at <anonymous> (http://localhost:8080/app.js:600:2), <anonymous>:126:14)
    at VueComponent.mounted (eval at <anonymous> (http://localhost:8080/app.js:1104:2), <anonymous>:25:10)
    at callHook (eval at <anonymous> (http://localhost:8080/app.js:600:2), <anonymous>:2610:19)
    at Object.insert (eval at <anonymous> (http://localhost:8080/app.js:600:2), <anonymous>:2802:5)
    at Object.def.(anonymous function) [as insert] (eval at <anonymous> (http://localhost:8080/app.js:600:2), <anonymous>:2150:17)
    at invokeInsertHook (eval at <anonymous> (http://localhost:8080/app.js:600:2), <anonymous>:4422:28)
    at VueComponent.patch [as __patch__] (eval at <anonymous> (http://localhost:8080/app.js:600:2), <anonymous>:4579:5)`

The way I'm doing the model

`<template>
<div class="users-create">

  <md-dialog md-open-from="#custom" md-close-to="#custom" ref="users-create-dialog">
    <md-dialog-title>Lorem ipsum dolor sit amet</md-dialog-title>

    <md-dialog-content>Nemo, nobis necessitatibus ut illo, ducimus ex.</md-dialog-content>

    <md-dialog-actions>
      <md-button class="md-primary" @click="closeDialog('users-create-dialog')">Cancel</md-button>
      <md-button class="md-primary" @click="closeDialog('users-create-dialog')">Ok</md-button>
    </md-dialog-actions>
  </md-dialog>

</div>
</template>`

In methods I create the component manipulation functions as shown in the examples on the page

`  methods: {

    openDialog(ref) {
      this.$refs[ref].open();
    },
    closeDialog(ref) {
      this.$refs[ref].close();
    },
    onOpen() {
      console.log('Opened');
    },
    onClose(type) {
      console.log('Closed', type);
    }

  }`

Then in mounted call the openDialog function

`  mounted() {

    this.openDialog('users-create-dialog')

  },`

**Comment by pablohpsilva** [comment]
You have to use the Dialog structure:

```
<md-dialog ref="users-create-dialog">
  <md-dialog-title>Lorem ipsum dolor sit amet</md-dialog-title>

  <md-dialog-content>Nemo, nobis necessitatibus ut illo, ducimus ex.</md-dialog-content>

  <md-dialog-actions>
    <md-button class="md-primary" @click="closeDialog('dialog1')">Cancel</md-button>
    <md-button class="md-primary" @click="closeDialog('dialog1')">Ok</md-button>
  </md-dialog-actions>
</md-dialog>
```

**Comment by pablohpsilva** [comment]
It turns out the `this.openDialog('users-create-dialog')` on `mounted()` was breaking it. It was trying to open a dialog but the dialog itself was not mounted yet.
