### ISSUE TITLE
md-select bug

### ISSUE THREAD

**Issue by alioygur** [marcosmoura/vue-material#66]
I am using v0.3 and I have a problem with md-select component.

When I use the md-select component I getting an error like these

```
vue.js?3de6:2611 [Vue warn]: Error when rendering component <md-input-container>: warn @ vue.js?3de6:2611Vue._render @ vue.js?3de6:2243(anonymous function) @ vue.js?3de6:1695get @ vue.js?3de6:740run @ vue.js?3de6:809flushSchedulerQueue @ vue.js?3de6:627nextTickHandler @ vue.js?3de6:405
vue.js?3de6:2252 Uncaught TypeError: Cannot read property 'constructor' of null
    at VueComponent.hasValue (eval at <anonymous> (http://localhost:8080/dist/build.js:1152:1), <anonymous>:6:27402)
    at Watcher.get (eval at <anonymous> (http://localhost:8080/dist/build.js:779:1), <anonymous>:740:27)
    at Watcher.evaluate (eval at <anonymous> (http://localhost:8080/dist/build.js:779:1), <anonymous>:848:21)
    at VueComponent.computedGetter [as hasValue] (eval at <anonymous> (http://localhost:8080/dist/build.js:779:1), <anonymous>:1309:15)
    at VueComponent.classes (eval at <anonymous> (http://localhost:8080/dist/build.js:1152:1), <anonymous>:6:27609)
    at Watcher.get (eval at <anonymous> (http://localhost:8080/dist/build.js:779:1), <anonymous>:740:27)
    at Watcher.evaluate (eval at <anonymous> (http://localhost:8080/dist/build.js:779:1), <anonymous>:848:21)
    at Proxy.computedGetter (eval at <anonymous> (http://localhost:8080/dist/build.js:779:1), <anonymous>:1309:15)
    at Proxy.render (eval at <anonymous> (http://localhost:8080/dist/build.js:1152:1), <anonymous>:9:3280)
    at VueComponent.Vue._render (eval at <anonymous> (http://localhost:8080/dist/build.js:779:1), <anonymous>:2240:22)
```

**Comment by marcosmoura** [comment]
Duplicated #72 #64
